apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: citary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: citary-database:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citary-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "my_database_pg"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc