apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: citary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: citary-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: citary-config
              key: VITE_API_URL